-- THIS FILE IS AUTOGENERATED. Add new entries by editing & running GenerateStatLocales.mts or StatLocaleData.json instead.
local addonName, addon = ...
if GetLocale() ~= "itIT" then return end
local StatLogic = LibStub(addonName)
local Stats = StatLogic.Stats

local W = addon.WholeTextLookup
W["riduce i danni inflitti, ma quando colpisce fornisce una probabilità di silenziare"] = { [Stats.AverageWeaponDamage] = -300, } -- s4242
W["sofferenza di taelan"] = { [Stats.AverageWeaponDamage] = 30, } -- s18810
W["so fast!"] = { [Stats.RangedHaste] = 150, [Stats.MeleeHit] = -75, [Stats.RangedHit] = -75, } -- s23674
W["ti senti felice"] = { [Stats.Spirit] = 50, } -- s25947
W["fai gli auguri ai tuoi amici!"] = { [Stats.Spirit] = 20, } -- s26004
W["brinda al tuo amico!"] = { [Stats.Stamina] = 20, } -- s26008
W["unisci un mucchio di biglietti, un sacco di pane artigianale e una raccolta di patti di roccavento per creare una collezione di doni di roccavento"] = { [Stats.Intellect] = 30, } -- s27664
W["unisci una cassa di birra artigianale, una raccolta di patti di forgiardente e una risma di biglietti per creare una collezione di doni di forgiardente"] = { [Stats.Stamina] = 30, } -- s27665
W["unisci una scatola di artigianato in legno, una raccolta di patti di darnassus e una pila di biglietti per creare una collezione di doni di darnassus"] = { [Stats.Agility] = 30, } -- s27666
W["unisci una scatola di dolci freschi, una raccolta di patti di orgrimmar e un pacco di biglietti per creare una collezione di doni di orgrimmar"] = { [Stats.Agility] = 30, } -- s27669
W["unisci un cesto di fiori, una sacca di biglietti e una raccolta di patti di picco del tuono per creare una collezione di doni di picco del tuono"] = { [Stats.Stamina] = 30, } -- s27670
W["unisci un libro dei poemi romantici, un faldone di biglietti e una raccolta di patti di sepulcra per creare una collezione di doni di sepulcra"] = { [Stats.Intellect] = 30, } -- s27671
W["raise a toast to your friend!"] = { [Stats.Stamina] = 10, [Stats.Stamina] = 10, } -- s29006
W["celebra un rituale che evoca il membro del gruppo selezionato. necessita la presenza dell'incantatore e di due altri membri del gruppo per completare il rituale. per partecipare, tutti i giocatori devono essere fuori dal combattimento e cliccare con il pulsante destro il portale, evitando qualsiasi movimento fino alla conclusione del rituale"] = { [Stats.FireResistance] = 10, [Stats.FireResistance] = 10, } -- s29134
W["il successivo attacco del famiglio è un critico, se tale attacco può infliggere danni critici"] = { [Stats.MeleeCrit] = 100, [Stats.RangedCrit] = 100, } -- s462214
W["clicca col pulsante destro per evocare e congedare il tuo serpente"] = { [Stats.Spirit] = 200, } -- s467754
W["judged by the power of the ashbringer. stunned, and armor and dodge chance are reduced"] = { [Stats.Dodge] = -50, } -- s1229508
W["if an enemy strikes the imbiber, the attacker is struck by a swift axe, pinning them to the ground temporarily"] = { [Stats.Armor] = 100, [Stats.FireResistance] = 100, [Stats.NatureResistance] = 100, [Stats.FrostResistance] = 100, [Stats.ShadowResistance] = 100, [Stats.ArcaneResistance] = 100, } -- s1309718
W["spezzato"] = { [Stats.AverageWeaponDamage] = -10, } -- e27
W["olio magico minore"] = { [Stats.SpellPower] = 8, } -- e2623
W["olio di mana minore"] = { [Stats.GenericManaRegen] = 5, [Stats.HealingPower] = 10, } -- e2624
W["olio magico inferiore"] = { [Stats.SpellPower] = 16, } -- e2626
W["olio magico"] = { [Stats.SpellPower] = 36, [Stats.SpellCrit] = 1, } -- e7644
W["olio di mana brillante"] = { [Stats.GenericManaRegen] = 15, [Stats.HealingPower] = 30, } -- e2629
W["frost"] = { [Stats.FrostDamage] = 8, } -- e8709
W["accuracy"] = { [Stats.HitRating] = 5, } -- e8711
W["flame"] = { [Stats.FireDamage] = 12, } -- e8713
W["greater flame"] = { [Stats.FireDamage] = 20, } -- e8716
W["greater frost"] = { [Stats.FrostDamage] = 20, } -- e8717
W["precision"] = { [Stats.CritRating] = 14, } -- e8718

local L = addon.StatIDLookup
L["protects the caster, increasing armor by %s and increases health regeneration by %s health per %s sec. for %s min"] = { { Stats.Armor, }, { Stats.HealthRegen, }, false, false, } -- s687
L["physical damage caused by the target is reduced by %s for %s min. only one curse per warlock can be active on any one target"] = { { Stats.AverageWeaponDamage, }, false, reduction = true } -- s702
L["protects the caster, increasing armor by %s, shadow resistance by %s and increases health regeneration by %s health per %s sec. for %s min"] = { { Stats.Armor, }, { Stats.ShadowResistance, }, { Stats.HealthRegen, }, false, false, } -- s706
L["aumenta la forza di %s e ti infligge %s danni ogni %s s per %s min"] = { { Stats.Strength, }, false, false, false, } -- s806
L["cura istantaneamente %s danni. rigenera %s mana in %s s. devi sederti per bere"] = { false, { Stats.GenericManaRegen, }, false, } -- s833
L["aumenta la resistenza al gelo e all'ombra di %s per %s min"] = { { Stats.FrostResistance, Stats.ShadowResistance, }, false, } -- s1138
L["forces the target to speak in demonic, increasing the casting time of all spells by %s%. only one curse per warlock can be active on any one target. lasts %s s"] = { { Stats.SpellHaste, }, false, reduction = true } -- s1714
L["aumenta permanentemente l'armatura di un oggetto indossato su torso, gambe, mani o piedi di %s"] = { { Stats.Armor, }, } -- s2831
L["aumenta la tua magia sacra di %s e riduce la tua resistenza all'ombra di %s"] = { false, { Stats.ShadowResistance, }, reduction = true } -- s2123
L["aumenta la tua resistenza a tutte le scuole di magia di %s per %s min"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, } -- s2380
L["rigenera %s salute e %s mana in %s s. devi sederti per mangiare"] = { false, { Stats.GenericManaRegen, }, false, } -- s2639
L["permanently increase the stamina value by %s and the armor value by %s of an item worn on the chest, legs, hands or feet"] = { { Stats.Stamina, }, { Stats.Armor, }, } -- s2832
L["stings the target, reducing the target's chance to hit with attacks by %s% for %s s. only one sting per hunter can be active on any one target"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, reduction = true } -- s3043
L["increases ranged and melee attack speed by %s% for %s s"] = { { Stats.RangedHaste, }, false, } -- s3045
L["riduce la forza dei nemici vicini di %s e l'agilità di %s per %s s"] = { { Stats.Strength, }, { Stats.Agility, }, false, reduction = true } -- s3146
L["permanently enchant a cloak to give %s agility"] = { { Stats.Agility, }, } -- s3231
L["aumenta la probabilità di parata dell'incantatore del %s% per %s s"] = { { Stats.Parry, }, false, } -- s3238
L["stordisce un nemico e riduce l'armatura di %s per %s s"] = { { Stats.Armor, }, false, reduction = true } -- s3263
L["aumenta la forza dell'incantatore di %s per %s min"] = { { Stats.Strength, }, false, } -- s3369
L["infonde nell'incantatore uno stato di furia che dura %s s, aumentando i danni fisici inflitti di %s e aumentando gli intervalli tra gli attacchi del %s%"] = { false, { Stats.AverageWeaponDamage, }, false, } -- s3416
L["aumenta la probabilità di blocco dell'incantatore del %s% per %s s"] = { { Stats.BlockChance, }, false, } -- s3419
L["aumenta la velocità d'attacco dell'incantatore del %s% per %s s, ma riduce i danni fisici inflitti di %s"] = { false, false, { Stats.AverageWeaponDamage, }, reduction = true } -- s3490
L["fa infuriare l'incantatore per %s s. aumenta la velocità d'attacco dell'incantatore del %s%, ma riduce la velocità di movimento del %s% e i danni fisici inflitti di %s"] = { false, false, false, { Stats.AverageWeaponDamage, }, reduction = true } -- s3547
L["riduce la velocità di lancio di un nemico del %s% per %s s"] = { { Stats.SpellHaste, }, false, reduction = true } -- s3603
L["lancia fango negli occhi del nemico, riducendo la probabilità d'impatto del %s% per %s s"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, reduction = true } -- s3650
L["applica in modo permanente un mirino a un arco o a un'arma da fuoco che aumenta i danni di %s"] = { { Stats.AverageWeaponDamage, }, } -- s3974
L["probabilità del %s% di aumentare l'armatura di %s per %s s quando subisci un attacco"] = { false, { Stats.Armor, }, false, ignoreSum = true } -- s4070
L["la tua resistenza agli incantesimi di gelo aumenta di %s"] = { { Stats.FrostResistance, }, } -- s4080
L["aumenta la probabilità di schivata del %s%. dura finché non è annullata"] = { { Stats.Dodge, }, } -- s4086
L["fa infuriare un bersaglio, attirando la sua attenzione e riducendo la sua armatura di %s"] = { { Stats.Armor, }, reduction = true } -- s4101
L["aumenta la forza dei membri del gruppo vicini di %s e l'agilità di %s per %s s"] = { { Stats.Strength, }, { Stats.Agility, }, false, } -- s4146
L["aggiunge %s forza e %s agilità ai membri del gruppo in un raggio di %s m per %s s"] = { { Stats.Strength, }, { Stats.Agility, }, false, false, } -- s4147
L["fornisce %s salute in più per %s min"] = { { Stats.Health, }, false, } -- s4148
L["aumenta l'armatura di %s per %s s"] = { { Stats.Armor, }, false, } -- s4149
L["aumenta la salute massima dei membri del gruppo di %s per %s min"] = { { Stats.Health, }, false, } -- s4238
L["aumenta il tuo mana di %s"] = { { Stats.Mana, }, } -- s4268
L["riduce la forza di %s e l'agilità di %s per %s s"] = { { Stats.Strength, }, { Stats.Agility, }, false, reduction = true } -- s4316
L["aumenta l'agilità di %s per %s min"] = { { Stats.Agility, }, false, } -- s4318
L["aumenta i danni con le spade a una mano di %s"] = { { Stats.AverageWeaponDamage, }, } -- s4352
L["aumenta la probabilità di critico con le spade a due mani del %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, } -- s4421
L["aumenta i danni con le asce a due mani di %s"] = { { Stats.AverageWeaponDamage, }, } -- s4443
L["aumenta i danni con le spade a due mani di %s"] = { { Stats.AverageWeaponDamage, }, } -- s4464
L["aumenta i danni inflitti con i bastoni di %s e fornisce una probabilità del %s% di stordire il bersaglio per %s s"] = { { Stats.AverageWeaponDamage, }, false, false, } -- s4493
L["aumenta di %s i danni inflitti dall'infernale, ma diminuisce la sua velocità d'attacco del %s% per %s s"] = { { Stats.AverageWeaponDamage, }, false, false, } -- s4539
L["aumenta la resistenza alla natura di %s"] = { { Stats.NatureResistance, }, } -- s4548
L["aumenta i danni dei tuoi incantesimi di gelo di %s"] = { { Stats.FrostDamage, }, } -- s4870
L["aumenta l'armatura di %s per %s min"] = { { Stats.Armor, }, false, } -- s4941
L["fornisce all'incantatore %s danni aggiuntivi per colpo per %s s, ma riduce la velocità di movimento del %s% e aumenta l'intervallo tra gli attacchi del %s%"] = { { Stats.AverageWeaponDamage, }, false, false, false, } -- s4955
L["rigenera %s salute in %s s. devi sederti per mangiare. se mangi per almeno %s secondi diventi ben nutrito e guadagni %s tempra e spirito per %s min"] = { false, false, false, { Stats.Stamina, }, false, ignoreSum = true } -- s5004
L["aumenta la probabilità di parata del %s%"] = { { Stats.Parry, }, } -- s5256
L["aumenta la tempra di %s e ti fa leggermente ubriacare"] = { { Stats.Stamina, }, } -- s5257
L["aumenta la tempra del bersaglio di %s per %s min"] = { { Stats.Spirit, }, false, } -- s5321
L["aumenta i danni con le spade a due mani di %s e la probabilità di parata con le spade a due mani del %s%"] = { { Stats.AverageWeaponDamage, }, false, } -- s5361
L["aumenta l'armatura di %s"] = { { Stats.Armor, }, } -- s5363
L["aumenta la probabilità di schivata dell'incantatore del %s% per %s s"] = { { Stats.Dodge, }, false, } -- s5426
L["aumenta i danni con le asce a due mani di %s e fornisce una probabilità del %s% di ridurre l'armatura del nemico di %s per %s s"] = { { Stats.AverageWeaponDamage, }, false, false, false, } -- s5427
L["riduce l'armatura del %s% per %s s"] = { { Stats.Armor, }, false, reduction = true } -- s5480
L["aumenta la probabilità di critico con le asce a una mano del %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, } -- s5509
L["riduce la probabilità d'impatto di un nemico del %s% per %s s"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, reduction = true } -- s5514
L["the enemy target is swarmed by insects, decreasing their chance to hit with attacks by %s% and causing %s nature damage over %s s"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, false, reduction = true } -- s5570
L["aumenta la probabilità di critico con i pugnali del %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, } -- s5586
L["aumenta i danni fisici di %s per %s min"] = { { Stats.AverageWeaponDamage, }, false, } -- s5665
L["rigenera %s salute ogni %s sec"] = { { Stats.HealthRegen, }, false, } -- s5707
L["l'energia sacra penetra nel bersaglio, aumentando la tempra di %s per %s min"] = { { Stats.Stamina, }, false, } -- s5862
L["reduces an enemy's chance to hit with attacks by %s% for %s s"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, reduction = true } -- s5884
L["questa birra leggera aumenta lo spirito di %s e riduce la tempra di %s per %s min"] = { { Stats.Spirit, }, { Stats.Stamina, }, false, } -- s5909
L["decreases target's chance to hit with attacks by %s% for %s s"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, reduction = true } -- s5917
L["aumenta l'intelletto di %s e riduce la tempra di %s per %s min"] = { { Stats.Intellect, }, { Stats.Stamina, }, false, } -- s6114
L["aumenta la salute del famiglio di %s"] = { { Stats.Health, }, } -- s6280
L["aumenta i danni inflitti dal famiglio di %s"] = { { Stats.AverageWeaponDamage, }, } -- s6311
L["aumenta lo spirito del famiglio di %s. necessita di addestramento"] = { { Stats.Spirit, }, } -- s6328
L["aumenta la resistenza del famiglio a tutte le scuole di magia di %s"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, } -- s6443
L["permanently enchant a cloak to give %s shadow resistance"] = { { Stats.ShadowResistance, }, } -- s6476
L["un filo tagliente che aumenta i danni dell'arma di %s"] = { { Stats.AverageWeaponDamage, }, } -- s6514
L["tosses dirt into an enemy's eyes, reducing its chance to hit with attacks by %s% for %s s"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, reduction = true } -- s6530
L["permette al tuo scorpione di entrare in modalità furtiva, ma non può muoversi e la sua portata visiva è ridotta. attaccando in questo stato, infligge %s danni aggiuntivi"] = { { Stats.AverageWeaponDamage, }, } -- s6538
L["riduce l'intelletto dei nemici vicini di %s per %s s"] = { { Stats.Intellect, }, false, reduction = true } -- s6818
L["aumenta i danni fisici dell'incantatore di %s, ma riduce la velocità di movimento del %s%. dura %s s"] = { { Stats.AverageWeaponDamage, }, false, false, } -- s6864
L["aumenta i danni fisici inflitti dall'incantatore di %s e aumenta la velocità di movimento del %s% per %s s. inoltre, maledice un nemico al primo colpo a segno, riducendo i danni fisici inflitti di %s, riducendo i danni magici inflitti di %s e aumentando i danni fisici subiti di %s per %s min"] = { { Stats.AverageWeaponDamage, }, false, false, { Stats.AverageWeaponDamage, }, { Stats.SpellDamage, }, false, false, } -- s6921
L["aumenta la forza di un alleato di %s per %s min"] = { { Stats.Strength, }, false, } -- s6957
L["aumenta i danni fisici inflitti dai membri del gruppo vicini di %s. il bersaglio amico può ricevere solo un'aura per paladino alla volta. l'aura dura finché non viene annullata"] = { { Stats.AverageWeaponDamage, }, } -- s7069
L["aumenta l'intervallo tra gli attacchi di un nemico del %s% e il tempo di lancio del %s%. inoltre, aggiunge una probabilità del %s% di contagiare un alleato all'impatto. dura %s min"] = { false, { Stats.SpellHaste, }, false, false, reduction = true } -- s7102
L["aumenta l'intervallo tra gli attacchi di un nemico del %s%, riduce la velocità di lancio del %s% e riduce la velocità di movimento del %s%. dura %s min"] = { false, { Stats.SpellHaste, }, false, false, reduction = true } -- s7127
L["reduces nearby enemies' chance to hit with attacks by %s% for %s s"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, reduction = true } -- s7272
L["aumenta lo spirito di %s"] = { { Stats.Spirit, }, } -- s7353
L["aumenta lo spirito dei membri del gruppo vicini di %s"] = { { Stats.Spirit, }, } -- s7363
L["%s forza"] = { { Stats.Strength, }, } -- s7464
L["%s intelletto"] = { { Stats.Intellect, }, } -- s7468
L["%s agilità"] = { { Stats.Agility, }, } -- s7471
L["%s spirito"] = { { Stats.Spirit, }, } -- s7474
L["%s tempra"] = { { Stats.Stamina, }, } -- s7477
L["aumenta l'intelletto di %s"] = { { Stats.Intellect, }, } -- s7764
L["trasforma in un serpente per %s min, aumentando i danni d'attacco di %s e aumentando l'intervallo tra gli attacchi del %s%"] = { false, { Stats.AverageWeaponDamage, }, false, } -- s7965
L["riduce la forza di un nemico di %s, l'agilità di %s e la tempra di %s per %s min"] = { { Stats.Strength, }, { Stats.Agility, }, { Stats.Stamina, }, false, reduction = true } -- s7997
L["trasforma in un serpente per %s s, aumentando i danni fisici del %s, ma sacrificando l'abilità di lanciare incantesimi"] = { false, { Stats.AverageWeaponDamage, }, } -- s8041
L["aumenta lo spirito di %s per %s min"] = { { Stats.Spirit, }, false, } -- s8068
L["una scarica di energia attraversa l'incantatore, aumentando i danni inflitti di %s e l'armatura di %s per %s s"] = { { Stats.AverageWeaponDamage, }, { Stats.Armor, }, false, } -- s8191
L["riduce l'armatura dei nemici vicini di %s per %s min"] = { { Stats.Armor, }, false, reduction = true } -- s8245
L["aumenta la velocità di movimento dell'incantatore del %s% per %s s e infligge %s danni aggiuntivi con il primo attacco"] = { false, false, { Stats.AverageWeaponDamage, }, } -- s8260
L["riduce i danni fisici causati dal bersaglio di %s per %s min"] = { { Stats.AverageWeaponDamage, }, false, reduction = true } -- s8277
L["aumenta i danni fisici inflitti da un alleato di %s per %s min"] = { { Stats.AverageWeaponDamage, }, false, } -- s8365
L["attack power increased by %s. granted %s extra attack"] = { { Stats.AttackPower, }, false, } -- s8516
L["riduce i danni inflitti dal bersaglio di %s per %s min"] = { { Stats.AverageWeaponDamage, }, false, reduction = true } -- s8552
L["finishing move that exposes the target for %s s, reducing armor per combo point:\r\n   %s point  : %s armor\r\n   %s points: %s armor\r\n   %s points: %s armor\r\n   %s points: %s armor\r\n   %s points: %s armor"] = { false, false, { Stats.Armor, }, false, false, false, false, false, false, false, false, } -- s8647
L["weakens the target enemy, reducing melee attack power by %s and reducing the effectiveness of any healing by %s%. lasts %s min"] = { { Stats.AttackPower, }, false, false, reduction = true } -- s9035
L["riduce l'armatura del bersaglio di %s per %s min"] = { { Stats.Armor, }, false, reduction = true } -- s9176
L["immobilizza il bersaglio e aumenta i danni fisici inflitti di %s per %s s"] = { { Stats.AverageWeaponDamage, }, false, } -- s9576
L["%s armatura"] = { { Stats.Armor, }, } -- s9760
L["riduce l'armatura del bersaglio di %s per %s s. mentre ne è affetto, il bersaglio non può entrare in modalità furtiva o diventare invisibile"] = { { Stats.Armor, }, false, reduction = true } -- s9806
L["sacrifica la vita dell'incantatore per ridurre la tempra dei nemici vicini di %s per %s min"] = { { Stats.Stamina, }, false, reduction = true } -- s10251
L["aumenta la velocità d'attacco degli alleati meccanici del %s% e aumenta i danni fisici inflitti di %s per %s s"] = { false, { Stats.AverageWeaponDamage, }, false, } -- s10732
L["assale il nemico con la rabbia di sul'thraze. riduce la forza del bersaglio di %s e infligge %s danni da ombra e %s danni aggiuntivi in %s s"] = { { Stats.Strength, }, false, false, false, reduction = true } -- s11658
L["danneggia l'armatura del bersaglio, riducendola di %s"] = { { Stats.Armor, }, reduction = true } -- s11791
L["riduce la forza dei nemici di %s e la tempra di %s per %s min"] = { { Stats.Strength, }, { Stats.Stamina, }, false, reduction = true } -- s11892
L["riduce la forza di un nemico di %s e la tempra di %s per %s min"] = { { Stats.Strength, }, { Stats.Stamina, }, false, reduction = true } -- s11963
L["inflicts %s nature damage to nearby enemies, reducing their chance to hit with attacks by %s% for %s s"] = { false, { Stats.MeleeHit, Stats.RangedHit, }, false, reduction = true } -- s11983
L["aumenta la probabilità di blocco dell'incantatore del %s% per %s s, ma blocca solamente %s attacco"] = { { Stats.BlockChance, }, false, false, } -- s12169
L["aumenta la probabilità di blocco dell'incantatore del %s% per %s s, ma blocca solamente %s attacchi"] = { { Stats.BlockChance, }, false, false, } -- s12169
L["riduce la velocità di lancio dei nemici vicini del %s% e aumenta l'intervallo tra gli attacchi del %s%. dura %s min"] = { { Stats.SpellHaste, }, false, false, reduction = true } -- s12255
L["increases your defense skill by %s"] = { { Stats.Defense, }, } -- s12297
L["increases your chance to block attacks with your shield by %s% and grants you a %s% chance to generate %s rage when you block"] = { { Stats.BlockChance, }, false, false, } -- s12298
L["improves your chance to get a critical strike with melee attacks by %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, } -- s12320
L["riduce gli attributi dei nemici vicini di %s per %s min"] = { { Stats.AllStats, }, false, reduction = true } -- s12530
L["increases attack power by %s and melee attack speed by %s% for %s s"] = { { Stats.AttackPower, }, false, false, } -- s12686
L["aumenta la rigenerazione normale di salute e mana di %s"] = { { Stats.GenericManaRegen, }, } -- s12732
L["increases all resistances by %s and grants immunity to fear for %s s"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, } -- s12733
L["costringe i nemici vicini a parlare in lingua demoniaca, riducendo la velocità di lancio del %s% per %s s. su un bersaglio può essere attiva solo una maledizione per stregone alla volta"] = { { Stats.SpellHaste, }, false, reduction = true } -- s12889
L["the hunter takes on the aspects of a beast, becoming untrackable and increasing melee attack power by %s. only one aspect can be active at a time"] = { { Stats.AttackPower, }, } -- s13161
L["aumenta i danni fisici inflitti dalla gallina del %s% e aumenta la velocità d'attacco della gallina del %s% per %s s"] = { { Stats.AverageWeaponDamage, }, false, false, } -- s13168
L["aumenta l'intelletto di un alleato di %s per %s min"] = { { Stats.Intellect, }, false, } -- s13326
L["riduce la probabilità di blocco del bersaglio del %s% per %s s"] = { { Stats.BlockChance, }, false, reduction = true } -- s13459
L["incanta in modo permanente uno scudo per aumentare lo spirito di %s"] = { { Stats.Spirit, }, } -- s13485
L["riduce la potenza d'attacco del bersaglio di %s per %s s"] = { { Stats.GenericAttackPower, }, false, reduction = true } -- s13490
L["lowers the attack power of the target by %s for %s min"] = { { Stats.AttackPower, }, false, reduction = true } -- s13524
L["corrosive acid that deals %s nature damage every $t sec and lowers target's armor by %s for %s s"] = { false, { Stats.Armor, }, false, reduction = true } -- s13526
L["reduces target enemy's attack power by %s for %s s"] = { { Stats.GenericAttackPower, }, false, reduction = true } -- s13528
L["incanta in modo permanente un mantello per aumentare l'armatura di %s"] = { { Stats.Armor, }, } -- s13635
L["permanently enchant bracers to give %s spirit"] = { { Stats.Spirit, }, } -- s13642
L["permanently enchant bracers to give %s stamina"] = { { Stats.Stamina, }, } -- s13648
L["permanently enchant bracers to give %s strength"] = { { Stats.Strength, }, } -- s13661
L["incanta in modo permanente un'armatura da torso per aumentare tutte le statistiche di %s"] = { { Stats.AllStats, }, } -- s13700
L["improves your chance to hit by %s%"] = { { Stats.MeleeHit, Stats.RangedHit, Stats.SpellHit, }, } -- s13705
L["increases your dodge chance by %s%"] = { { Stats.Dodge, }, } -- s13712
L["aumenta la tua probabilità di parata del %s%"] = { { Stats.Parry, }, } -- s13713
L["increases fire resistance by %s and absorbs %s fire damage.  lasts %s s"] = { { Stats.FireResistance, }, false, false, } -- s13744
L["incanta in modo permanente un mantello per aumentare tutte le resistenze di %s"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, } -- s13794
L["permanently enchant bracers to give %s intellect"] = { { Stats.Intellect, }, } -- s13822
L["incanta in modo permanente degli stivali per aumentare la tempra di %s"] = { { Stats.Stamina, }, } -- s13836
L["permanently enchant bracers to give %s defense"] = { { Stats.Defense, }, } -- s13931
L["incanta in modo permanente degli stivali per aumentare l'agilità di %s"] = { { Stats.Agility, }, } -- s13935
L["erode l'armatura del nemico, riducendola di %s per ogni applicazione. accumulabile fino a %s volte. dura %s s"] = { { Stats.Armor, }, false, false, } -- s14120
L["riduce la velocità di lancio dei nemici vicini del %s% per %s min"] = { { Stats.SpellHaste, }, false, reduction = true } -- s14538
L["%s resistenza al fuoco"] = { { Stats.FireResistance, }, } -- s14540
L["%s resistenza al gelo"] = { { Stats.FrostResistance, }, } -- s14541
L["%s resistenza alla natura"] = { { Stats.NatureResistance, }, } -- s14622
L["%s resistenza all'ombra"] = { { Stats.ShadowResistance, }, } -- s14663
L["%s resistenza all'arcano"] = { { Stats.ArcaneResistance, }, } -- s14664
L["aumenta la velocità d'attacco dell'incantatore del %s% e aumenta i danni fisici inflitti di %s per %s s"] = { false, { Stats.AverageWeaponDamage, }, false, } -- s14872
L["aumenta la probabilità di schivata del ladro del %s% per %s s"] = { { Stats.Dodge, }, false, } -- s15087
L["aumenta la resistenza al fuoco di un alleato di %s per %s ora"] = { { Stats.FireResistance, }, false, } -- s15123
L["riduce l'armatura di un bersaglio nemico di %s per %s min"] = { { Stats.Armor, }, false, reduction = true } -- s15235
L["riduce l'armatura del bersaglio di %s per %s s"] = { { Stats.Armor, }, false, reduction = true } -- s15280
L["aumenta i danni magici inflitti da un alleato di %s per %s min"] = { { Stats.SpellDamage, }, false, } -- s15288
L["colpisce l'armatura dei nemici vicini, riducendola di %s per ogni applicazione di fendi armatura. accumulabile fino a %s volte. dura %s s"] = { { Stats.Armor, }, false, false, } -- s15502
L["aumenta la potenza d'attacco di %s per %s s"] = { { Stats.GenericAttackPower, }, false, } -- s15602
L["avvolge un alleato con uno strato di ghiaccio che dura %s min. lo strato di ghiaccio aumenta l'armatura di %s; inoltre, rallenta la velocità di movimento degli attaccanti al %s% e aumenta l'intervallo tra gli attacchi del %s%"] = { false, { Stats.Armor, }, false, false, } -- s15784
L["riduce tutti gli attributi di un nemico di %s per %s min"] = { { Stats.AllStats, }, false, reduction = true } -- s15848
L["aumenta la resistenza a tutte le scuole di magia di %s"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, } -- s15967
L["reduces the mana cost of your healing spells by %s% and improves your chance to hit by %s%"] = { false, { Stats.MeleeHit, Stats.RangedHit, Stats.SpellHit, }, } -- s16179
L["aumenta la potenza d'attacco di un nemico di %s, ma riduce la sua armatura di %s per %s min. i nemici maledetti ignorano gli effetti di paura e non fuggono dal combattimento. su un bersaglio può essere attiva solo una maledizione per stregone alla volta"] = { { Stats.AttackPower, }, { Stats.Armor, }, false, } -- s16231
L["riduce la resistenza all'ombra di un nemico di %s per %s min"] = { { Stats.ShadowResistance, }, false, reduction = true } -- s16429
L["riduce la probabilità di schivata di un nemico del %s% per %s min"] = { { Stats.Dodge, }, false, reduction = true } -- s16448
L["riduce la potenza d'attacco in mischia di un nemico di %s e la sua potenza d'attacco a distanza di %s per %s min"] = { { Stats.GenericAttackPower, }, false, false, reduction = true } -- s16449
L["blasts a target for %s fire damage and increases fire damage done to target by %s for %s s"] = { false, { Stats.FireDamage, }, false, } -- s16454
L["riduce la velocità di movimento di un nemico del %s% e riduce i danni fisici e magici inflitti di %s. dura %s min"] = { false, { Stats.SpellDamage, }, false, reduction = true } -- s16458
L["riduce la probabilità di critico in mischia di un nemico del %s% e riduce la probabilità di critico con gli incantesimi del %s%. dura %s min"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, { Stats.SpellCrit, }, false, reduction = true } -- s16460
L["increases your parry chance by %s%"] = { { Stats.Parry, }, } -- s16462
L["aumenta l'armatura di %s per %s s, ma non puoi lanciare incantesimi o attaccare per tutta la durata dell'incantesimo"] = { { Stats.Armor, }, false, } -- s16470
L["riduce l'armatura di un nemico di %s per %s min. sotto l'effetto di questo incantesimo, il bersaglio non può muoversi furtivamente o diventare invisibile"] = { { Stats.Armor, }, false, reduction = true } -- s16498
L["aumenta i danni da ombra inflitti da un alleato di %s per %s min"] = { { Stats.ShadowDamage, }, false, } -- s16587
L["aumenta la forza di %s"] = { { Stats.Strength, }, } -- s16612
L["aumenta la tempra di %s. dura %s min"] = { { Stats.Stamina, }, false, } -- s16617
L["aumenta i danni fisici inflitti dall'incantatore di %s e la sua velocità d'attacco del %s% per %s s"] = { { Stats.AverageWeaponDamage, }, false, false, } -- s16789
L["increases the range of your offensive balance spells by %s% and improves your chance to hit by %s%"] = { false, { Stats.MeleeHit, Stats.RangedHit, Stats.SpellHit, }, } -- s16819
L["il nemico è afflitto dalla maledizione spaccalegna, che riduce le resistenze magiche di %s. accumulabile fino a %s volte"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, reduction = true } -- s16871
L["holy power infuses the target increasing their stamina by %s for %s min"] = { { Stats.Stamina, }, false, } -- s16873
L["l'energia sacra potenzia il bersaglio, aumentando lo spirito di %s per %s min"] = { { Stats.Spirit, }, false, } -- s16875
L["aumenta l'intelletto del bersaglio di %s per %s min"] = { { Stats.Intellect, }, false, } -- s16876
L["aumenta l'armatura di un bersaglio amico di %s, gli attributi di %s e le resistenze di %s per %s min"] = { { Stats.Armor, }, { Stats.AllStats, }, false, false, } -- s16878
L["aumenta la forza di %s, la tempra di %s e le dimensioni per %s min"] = { { Stats.Strength, }, { Stats.Stamina, }, false, } -- s16883
L["aumenta la salute massima del giocatore di %s per %s ora"] = { { Stats.Health, }, false, } -- s16884
L["aumenta l'agilità di %s per %s ora"] = { { Stats.Agility, }, false, } -- s16885
L["aumenta l'intelletto di %s per %s ora"] = { { Stats.Intellect, }, false, } -- s16888
L["aumenta i danni magici di %s per %s min"] = { { Stats.SpellDamage, }, false, } -- s16889
L["rigenera %s salute ogni %s s per %s ora"] = { { Stats.HealthRegen, }, false, false, } -- s16890
L["heal yourself for %s and increase your strength by %s for %s s"] = { false, { Stats.Strength, }, false, } -- s16916
L["riduce l'armatura di un nemico di %s. si accumula fino a %s volte"] = { { Stats.Armor, }, false, reduction = true } -- s16928
L["increases your movement speed while in cat form by %s%, and increases your chance to dodge by %s%"] = { false, { Stats.Dodge, }, } -- s17002
L["aumenta l'agilità di %s"] = { { Stats.Agility, }, } -- s17013
L["wounds the target's head, dealing %s physical damage, and increasing the casting time of all spells by %s% for %s s"] = { false, { Stats.SpellHaste, }, false, reduction = true } -- s17148
L["aumenta la forza di %s per %s s"] = { { Stats.Strength, }, false, } -- s17152
L["infligge %s danni da natura agli attaccanti all'impatto e aumenta la resistenza alla natura di %s per %s s"] = { false, { Stats.NatureResistance, }, false, } -- s17154
L["aumenta la resistenza all'arcano di un alleato di %s per %s ora"] = { { Stats.ArcaneResistance, }, false, } -- s17175
L["difesa %s. un autentico hardcore player da urlo!"] = { { Stats.Defense, }, } -- s17178
L["aumenta la potenza d'attacco in mischia dell'incantatore di %s per %s min"] = { { Stats.AttackPower, }, false, } -- s17205
L["riduce i danni magici inflitti da un nemico di %s per %s min. su un bersaglio può essere attiva solo una maledizione per stregone alla volta"] = { { Stats.AverageWeaponDamage, }, false, reduction = true } -- s17227
L["prende il controllo di un nemico umanoide fino al livello %s per %s min e ne aumenta la salute massima del %s%"] = { false, false, { Stats.Health, }, } -- s17244
L["aumenta la resistenza al fuoco di %s e infligge %s danni da fuoco a chiunque ti colpisca in mischia per %s min"] = { { Stats.FireResistance, }, false, false, } -- s17275
L["punctures target's armor lowering it by %s. can be applied up to %s times"] = { { Stats.Armor, }, false, reduction = true } -- s17315
L["riduce il tempo di lancio del bersaglio nemico e aumenta l'intervallo tra gli attacchi in mischia e a distanza del %s% per %s s"] = { { Stats.SpellHaste, Stats.RangedHaste, }, false, reduction = true } -- s17331
L["chance on hit: immobilizes the target and lowers their armor by %s for %s s"] = { { Stats.Armor, }, false, ignoreSum = true, reduction = true } -- s17332
L["has a chance when struck in combat to increase your chance to block by %s% for %s s. undead that strike you are %s times as likely to activate this effect"] = { { Stats.BlockChance, }, false, false, ignoreSum = true } -- s17350
L["chance to block increased by %s%"] = { { Stats.BlockChance, }, } -- s17351
L["increases attack power by %s, and attack power against undead by an additional %s for %s s"] = { { Stats.GenericAttackPower, }, false, false, } -- s17352
L["increases movement speed by %s% and restores %s health every %s"] = { false, { Stats.HealthRegen, }, false, } -- s17625
L["increases the player's maximum health by %s for %s ore. you can only have the effect of one flask at a time. this effect persists through death"] = { { Stats.Health, }, false, } -- s17626
L["increases damage done by magical spells and effects by up to %s for %s ore. you can only have the effect of one flask at a time. this effect persists through death"] = { { Stats.SpellDamage, }, false, } -- s17628
L["increases your resistance to all schools of magic by %s for %s ore. you can only have the effect of one flask at a time. this effect persists through death and stacks with all other resistance spells and items"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, } -- s17629
L["aumenta la velocità di lancio di un alleato del %s% per %s s"] = { { Stats.SpellHaste, }, false, } -- s17633
L["circonda l'incantatore con un'aura che riduce periodicamente la resistenza all'ombra dei nemici vicini di %s. l'aura dura finché non viene annullata"] = { { Stats.ShadowResistance, }, ignoreSum = true, reduction = true } -- s17695
L["aumenta la forza di %s per %s min"] = { { Stats.Strength, }, false, } -- s18125
L["riduce la resistenza alla natura di un nemico di %s per %s min"] = { { Stats.NatureResistance, }, false, reduction = true } -- s18151
L["improves your chance to hit by %s% and reduces all threat you generate by %s%"] = { { Stats.SpellHit, Stats.MeleeHit, Stats.RangedHit, }, false, } -- s18174
L["aumenta la tempra di %s per %s min"] = { { Stats.GenericAttackPower, Stats.RangedAttackPower, }, false, } -- s1249519
L["restores %s health over %s s.   must remain seated while eating.   if you eat for %s seconds will also increase your agility by %s for %s min"] = { false, false, false, { Stats.Agility, }, false, ignoreSum = true } -- s18230
L["fornisce %s intelletto aggiuntivo ai membri del gruppo entro %s m"] = { { Stats.Intellect, }, false, } -- s18264
L["rigenera %s mana ogni %s s"] = { { Stats.SpellPower, Stats.GenericAttackPower, }, false, } -- s439155
L["riduce la potenza d'attacco del bersaglio nemico di %s per %s s"] = { { Stats.GenericAttackPower, }, false, reduction = true } -- s18381
L["morde un nemico, riducendo forza e agilità di %s per %s s"] = { { Stats.Strength, Stats.Agility, }, false, reduction = true } -- s18545
L["deals %s shadow damage every %s sec for %s s and lowers their attack power by %s for %s s"] = { false, false, false, { Stats.AttackPower, }, false, reduction = true } -- s18633
L["%s tutte le resistenze"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, } -- s18672
L["in seguito a un attacco, fornisce il %s% di probabilità di creare un rivestimento osseo che aumenta l'armatura di %s per %s s"] = { false, { Stats.Armor, }, false, } -- s18828
L["increases armor by %s for %s s"] = { { Stats.Armor, }, false, } -- s18946
L["brucia un nemico per %s danni e riduce la resistenza al fuoco di %s per %s s"] = { false, { Stats.FireResistance, }, false, reduction = true } -- s18958
L["riduce la velocità di lancio di un nemico del %s% e aumenta l'intervallo tra gli attacchi del %s% per %s min"] = { { Stats.SpellHaste, }, false, false, reduction = true } -- s19365
L["riduce la resistenza al fuoco dei nemici vicini di %s per %s min"] = { { Stats.FireResistance, }, false, reduction = true } -- s19366
L["increases the ranged attack power of party members within %s yards by %s. lasts %s min"] = { false, { Stats.RangedAttackPower, }, false, } -- s19506
L["aumenta tutte le resistenze di %s per %s s"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, } -- s19638
L["if you spend at least %s seconds eating you will become well fed and gain %s stamina and spirit for %s min"] = { false, { Stats.Stamina, Stats.Spirit, }, false, } -- s19708
L["riduce la potenza d'attacco in mischia e a distanza dei nemici vicini di %s per %s s"] = { { Stats.GenericAttackPower, }, false, reduction = true } -- s19778
L["gives %s additional shadow resistance to all party and raid members within %s yards. players may only have one aura on them per paladin at any one time"] = { { Stats.ShadowResistance, }, false, } -- s19876
L["gives %s additional frost resistance to all party and raid members within %s yards. players may only have one aura on them per paladin at any one time"] = { { Stats.FrostResistance, }, false, } -- s19888
L["gives %s additional fire resistance to all party and raid members within %s yards. players may only have one aura on them per paladin at any one time"] = { { Stats.FireResistance, }, false, } -- s19891
L["permanently enchant a cloak to give %s fire resistance"] = { { Stats.FireResistance, }, } -- s19932
L["cura di %s e aumenta la forza di %s per %s s"] = { false, { Stats.Strength, }, false, } -- s20007
L["the hunter and all party and raid members within %s yards take on the aspect of the wild, increasing nature resistance by %s.  only one aspect can be active at a time"] = { false, { Stats.NatureResistance, }, } -- s20043
L["power infuses all party and raid members, increasing their stamina by %s for %s ora"] = { { Stats.Stamina, }, false, } -- s21562
L["total health increased by %s% and chance to hit increased by %s%"] = { false, { Stats.MeleeHit, Stats.RangedHit, Stats.SpellHit, }, } -- s20550
L["dodge chance increased by %s% and movement speed increased by %s%. night elf rogues and druids are harder to detect in stealth as if they were %s level higher"] = { { Stats.Dodge, }, false, false, } -- s20582
L["increases stamina by %s and reduces physical damage taken by %s for %s min. however, lowers strength and agility by %s and increases magical damage taken by up to %s"] = { { Stats.Stamina, }, false, false, { Stats.Strength, Stats.Agility, }, false, } -- s20587
L["cura un alleato di %s danni ogni %s s e aumenta la sua armatura di %s per %s min"] = { false, false, { Stats.Armor, }, false, } -- s20655
L["prende il controllo di un nemico umanoide fino al livello %s per %s s, aumenta i danni magici inflitti di %s e aumenta i danni fisici inflitti di %s"] = { false, false, { Stats.SpellDamage, }, { Stats.AverageWeaponDamage, }, } -- s20668
L["riduce la potenza d'attacco in mischia dei nemici vicini di %s per %s s"] = { { Stats.AttackPower, }, false, reduction = true } -- s20753
L["when struck in combat has a %s% chance of increasing all party member's armor by %s for %s s. this chance is doubled in strongholds and cities"] = { false, { Stats.Armor, }, false, ignoreSum = true } -- s20847
L["aumenta la tempra di %s per %s min e infonde ubriachezza molesta!"] = { { Stats.Stamina, }, false, } -- s20875
L["assoggetta il demone bersaglio, fino al livello %s, piegandolo al tuo volere. mentre è assoggettato, l'intervallo tra gli attacchi del demone è aumentato del %s% e la sua velocità di lancio è ridotta del %s%. dura fino a %s min"] = { false, false, { Stats.SpellHaste, }, false, reduction = true } -- s20882
L["rigenera %s salute ogni %s s"] = { { Stats.HealthRegen, }, false, } -- s20885
L["increases chance to block by %s% for %s s, and deals %s holy damage for each attack blocked while active.  damage caused by holy shield causes %s% additional threat. each block expends a charge. %s charges"] = { { Stats.BlockChance, }, false, false, false, false, } -- s20925
L["increases chance to block by %s% for %s s, and deals %s holy damage for each attack blocked while active. damage caused by holy shield causes %s% additional threat"] = { { Stats.BlockChance, }, false, false, false, } -- s20927
L["colpisce l'armatura del nemico, riducendola di %s per ogni applicazione di schiacciarmatura. accumulabile fino a %s volte. dura %s s"] = { { Stats.Armor, }, false, false, } -- s21055
L["lancia un dardo d'ombra contro il nemico, infliggendo %s danni da ombra e riducendo tutte le statistiche di %s per %s s"] = { false, { Stats.AllStats, }, false, reduction = true } -- s21151
L["rigenera %s salute e %s mana al secondo in prossimità di un comandante"] = { { Stats.HealthRegen, }, false, } -- s21172
L["rigenera %s salute e %s mana al secondo in prossimità di un tenente"] = { { Stats.HealthRegen, }, false, } -- s21174
L["riduce la probabilità di parare un attacco del %s%"] = { { Stats.Parry, }, reduction = true } -- s21352
L["il tuo famiglio ottiene %s tempra e %s resistenza magica a tutte le scuole di magia"] = { { Stats.Stamina, }, false, ignoreSum = true } -- s21741
L["gives the gift of the wild to all party and raid members, increasing armor by %s, all attributes by %s and all resistances by %s for %s ora"] = { { Stats.Armor, }, { Stats.AllStats, }, false, false, } -- s21849
L["la probabilità di schivata del ladro aumenta del %s% per %s s"] = { { Stats.Dodge, }, false, } -- s21878
L["aumenta la tempra del tuo famiglio di %s e la resistenza agli incantesimi di %s"] = { { Stats.Stamina, }, false, ignoreSum = true } -- s21926
L["ferisce il bersaglio per %s danni e riduce la sua armatura di %s"] = { false, { Stats.Armor, }, reduction = true } -- s21961
L["has a %s% chance when struck in combat of increasing all stats by %s for %s min"] = { false, { Stats.AllStats, }, false, ignoreSum = true } -- s21969
L["aumenta le tue statistiche di %s per %s min"] = { { Stats.AllStats, }, false, } -- s21970
L["travolge il nemico con la potenza del fulmine, infliggendo %s danni da natura e colpendo nemici aggiuntivi vicini. ogni passaggio riduce la resistenza alla natura della vittima di %s. affligge %s bersagli. inoltre, il bersaglio primario viene travolto da un ciclone, che riduce la velocità d'attacco del %s% per %s s"] = { false, { Stats.NatureResistance, }, false, false, false, reduction = true } -- s21992
L["permanently enchants bracers to give %s strength"] = { { Stats.Strength, }, } -- s22051
L["permanently enchants bracers to give %s stamina"] = { { Stats.Stamina, }, } -- s22052
L["permanently enchants bracers to give %s spirit"] = { { Stats.Spirit, }, } -- s22053
L["permanently enchants bracers to give %s intellect"] = { { Stats.Intellect, }, } -- s22054
L["permanently enchant a piece of chest armor to grant %s health"] = { { Stats.Stamina, }, } -- s22089
L["permanently enchant a cloak to give %s to all resistances"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, } -- s22091
L["permanently enchant a cloak to give %s additional armor"] = { { Stats.Armor, }, } -- s22092
L["permanently enchant a two-handed melee weapon to do %s damage"] = { { Stats.AverageWeaponDamage, }, } -- s22094
L["permanently enchant a melee weapon to do %s additional points of damage"] = { { Stats.AverageWeaponDamage, }, } -- s22095
L["permanently enchant a shield to give %s stamina"] = { { Stats.Stamina, }, } -- s22098
L["permanently enchant a shield to give %s frost resistance"] = { { Stats.FrostResistance, }, } -- s22099
L["permanently enchant a shield to give %s spirit"] = { { Stats.Spirit, }, } -- s22100
L["permanently enchant boots to give %s agility"] = { { Stats.Agility, }, } -- s22101
L["permanently enchant boots to give %s spirit"] = { { Stats.Spirit, }, } -- s22102
L["permanently enchant boots to give %s stamina"] = { { Stats.Stamina, }, } -- s22103
L["permanently enchant gloves to grant %s strength"] = { { Stats.Strength, }, } -- s22104
L["permanently enchant gloves to grant %s agility"] = { { Stats.Agility, }, } -- s22105
L["aumenta casualmente i danni magici inflitti dall'incantatore fino a %s per %s min"] = { { Stats.SpellDamage, }, false, } -- s22418
L["riduce la tempra dei nemici vicini di %s per %s min"] = { { Stats.Stamina, }, false, reduction = true } -- s22420
L["increases defense skill by %s for %s min"] = { { Stats.Defense, }, false, } -- s22685
L["aumenta l'intelletto di %s per %s min"] = { { Stats.Intellect, }, false, } -- s22730
L["a razor edge improves your chance to get a critical strike by %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, } -- s22755
L["aumenta la tempra di %s per %s min e genera un'ubriachezza non comune. verde significa buono!"] = { { Stats.Stamina, }, false, } -- s22789
L["attack power increased by %s and spell damage and healing increased by up to %s"] = { { Stats.GenericAttackPower, }, { Stats.SpellDamage, }, } -- s22817
L["grants the wielder %s defense, %s armor, %s attack power, and %s additional attack power against dragonkin for %s s"] = { { Stats.Defense, }, { Stats.Armor, }, { Stats.AttackPower, }, false, false, } -- s22850
L["infuses the target's party and raid with brilliance, increasing their intellect by %s for %s ora"] = { { Stats.Intellect, }, false, } -- s23028
L["permanently enchant a melee weapon to add up to %s damage to spells"] = { { Stats.SpellPower, }, } -- s23143
L["permanently enchant a melee weapon to add up to %s points of healing to healing spells"] = { { Stats.HealingPower, }, } -- s23144
L["improves your chance to get a critical strike with spells by %s%"] = { { Stats.SpellCrit, }, } -- s23440
L["aumenta la velocità d'attacco dell'incantatore del %s% e i danni fisici inflitti di %s per %s min"] = { false, { Stats.AverageWeaponDamage, }, false, } -- s23537
L["increases your off-hand weapon damage by %s% and chance to hit with off-hand attacks by %s%"] = { false, { Stats.MeleeHit, Stats.RangedHit, }, } -- s23584
L["%s% chance on successful spellcast to increase your spirit by %s for %s s"] = { false, { Stats.Spirit, }, false, } -- s23684
L["aumenta l'armatura di %s e cura %s danni ogni volta che subisci danni in mischia o a distanza per %s s"] = { { Stats.Armor, }, false, false, } -- s23780
L["permanently enchant bracers to restore %s mana every %s seconds"] = { { Stats.GenericManaRegen, }, false, } -- s23801
L["permanently enchant bracers to increase the effects of your healing spells by up to %s and the effects of your damage spells by up to %s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s23802
L["potenzia il bersaglio, aumentando la tempra di %s per %s ora"] = { { Stats.Stamina, }, false, } -- s23947
L["quando è attivo, aumenta la probabilità di critico con attacchi e incantesimi del bersaglio del %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, Stats.SpellCrit, }, } -- s23964
L["aumenta i danni inflitti di %s per %s s"] = { { Stats.AverageWeaponDamage, }, false, } -- s24043
L["riduce l'armatura di un nemico di %s e infligge %s danni da natura ogni %s s per %s s"] = { { Stats.Armor, }, false, false, false, reduction = true } -- s24111
L["%s attack power"] = { { Stats.AttackPower, Stats.RangedAttackPower, }, } -- e8691
L["infonde nell'incantatore una benedizione degli dei primordiali, aumentando la potenza d'attacco in mischia e a distanza di %s per %s s"] = { { Stats.GenericAttackPower, }, false, } -- s24255
L["fornisce una probabilità all'attacco in mischia o a distanza a segno di infondere nel portatore una benedizione degli dei primordiali. potenza d'attacco in mischia e a distanza aumentata di %s per %s s"] = { { Stats.GenericAttackPower, }, false, ignoreSum = true } -- s24256
L["colpisce l'armatura del nemico, riducendola di %s per ogni applicazione di fendi armatura. accumulabile fino a %s volte. dura %s s"] = { { Stats.Armor, }, false, false, reduction = true } -- s24317
L["ferisce il bersaglio per %s danni e riduce l'intelletto del bersaglio di %s per %s s"] = { false, { Stats.Intellect, }, false, reduction = true } -- s24388
L["aumenta l'intervallo tra gli attacchi dei nemici vicini del %s%, riduce la velocità di movimento del %s% e riduce la velocità di lancio del %s% per %s s"] = { false, false, { Stats.SpellHaste, }, false, reduction = true } -- s24415
L["rigenera %s salute ogni %s s e aumenta la forza di %s. dura %s min"] = { { Stats.HealthRegen, }, false, { Stats.Strength, }, false, } -- s24427
L["aumenta la potenza d'attacco in mischia dei membri del gruppo vicini di %s per %s s"] = { { Stats.AverageWeaponDamage, }, false, } -- s24438
L["increases the critical hit chance of spells by %s% for %s s"] = { { Stats.SpellCrit, }, false, } -- s24498
L["the wolf howls, increasing the melee attack power of all party members within %s yards by %s.  lasts %s min"] = { false, { Stats.AttackPower, }, false, } -- s24597
L["rigenera %s salute in %s s. devi sederti per mangiare. se mangi per almeno %s secondi diventi ben nutrito e guadagni %s forza per %s min"] = { false, false, false, { Stats.Strength, }, false, ignoreSum = true } -- s24800
L["%s danni dell'arma"] = { { Stats.AverageWeaponDamage, }, } -- s25901
L["while applied to target weapon it increases spell damage and healing by up to %s. lasts for %s minutes"] = { { Stats.SpellPower, }, false, } -- s25119
L["infligge danni normali più %s a un nemico e agli alleati vicini, affliggendo fino a %s bersagli. inoltre, gli attacchi riducono l'armatura di %s"] = { false, false, { Stats.Armor, }, reduction = true } -- s25174
L["rigenera %s mana in %s s. devi sederti per mangiare"] = { { Stats.GenericManaRegen, }, false, } -- s25701
L["fornisce una probabilità in seguito a un incantesimo d'attacco di ridurre le resistenze magiche dei bersagli dei tuoi incantesimi di %s per %s s"] = { { Stats.SpellPenetration, }, false, ignoreSum = true } -- s25767
L["indebolisce il bersaglio nemico, riducendo i danni inflitti di %s per %s min"] = { { Stats.AverageWeaponDamage, }, false, reduction = true } -- s25816
L["target gets %s% melee crit"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, } -- s25848
L["aumenta la potenza d'attacco in mischia e a distanza di %s. dura %s s"] = { { Stats.GenericAttackPower, }, false, } -- s25891
L["fornisce una probabilità in seguito a un incantesimo d'attacco di aumentare danni di effetti e incantesimi di %s per %s s"] = { { Stats.SpellDamage, }, false, ignoreSum = true } -- s25906
L["fornisce il %s% di probabilità d'impatto magico per %s s quando uno dei tuoi incantesimi è resistito"] = { { Stats.SpellHit, }, false, ignoreSum = true } -- s26128
L["infligge il %s% dei danni dell'arma e sbilancia il bersaglio, riducendo la sua abilità di difesa di %s per %s s"] = { false, { Stats.Defense, }, false, reduction = true } -- s26613
L["rigenera %s mana al secondo"] = { { Stats.GenericManaRegen, }, } -- s26647
L["permanently enchant a melee weapon to add %s to spirit"] = { { Stats.Spirit, }, } -- s26743
L["permanently enchant a melee weapon to add %s to agility"] = { { Stats.Agility, }, } -- s26792
L["permanently enchant a melee weapon to add %s to intellect"] = { { Stats.Intellect, }, } -- s26793
L["aumenta la probabilità di critico del famiglio del %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, ignoreSum = true } -- s27043
L["permanently enchant a melee weapon to add %s to strength"] = { { Stats.Strength, }, } -- s27093
L["permanently enchant a piece of chest armor to grant %s to all stats"] = { { Stats.AllStats, }, } -- s27107
L["permanently enchant gloves to increase the caster's healing spells by up to %s"] = { { Stats.HealingPower, }, } -- s27111
L["permanently enchant gloves to increase agility by %s"] = { { Stats.Agility, }, } -- s27112
L["permanently enchants bracers to restore %s mana every %s seconds"] = { { Stats.GenericManaRegen, }, false, } -- s27115
L["permanently enchants bracers to increase the effects of your healing spells by %s"] = { { Stats.HealingPower, }, } -- s27116
L["permanently enchant a shield to give %s% chance to block"] = { { Stats.BlockChance, }, } -- s27117
L["permanently enchant a cloak to give %s nature resistance"] = { { Stats.NatureResistance, }, } -- s27119
L["permanently enchant a cloak to give a %s% chance to dodge"] = { { Stats.Dodge, }, } -- s27122
L["il guerriero urla, aumentando la potenza d'attacco dei membri del gruppo entro %s m di %s. dura %s min"] = { false, { Stats.AttackPower, }, false, } -- s27578
L["riduce la potenza d'attacco dei nemici entro %s m di %s per %s s"] = { false, { Stats.GenericAttackPower, }, false, reduction = true } -- s27579
L["aumenta tutte le resistenze magiche di %s per %s min"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, } -- s27652
L["power infuses all party and raid members, increasing their spirit by %s for %s ora"] = { { Stats.Spirit, }, false, } -- s27681
L["power infuses all party and raid members, increasing their shadow resistance by %s for %s min"] = { { Stats.ShadowResistance, }, false, } -- s27683
L["improves your chance to hit with attacks by %s% for %s ora"] = { { Stats.MeleeHit, Stats.RangedHit, }, false, } -- s27723
L["aggiunge in modo permanente %s resistenza alla natura a un oggetto che si indossa sulle gambe o in testa. non cumulabile con altri incantamenti per oggetti simili"] = { { Stats.NatureResistance, }, } -- s28161
L["aggiunge in modo permanente %s resistenza all'ombra a un oggetto che si indossa sulle gambe o in testa. non cumulabile con altri incantamenti per oggetti simili"] = { { Stats.ShadowResistance, }, } -- s28165
L["aumenta la salute del bersaglio amico fino a %s per %s s"] = { { Stats.Health, }, false, } -- s28750
L["aumenta la resistenza al fuoco di %s. dura %s s"] = { { Stats.FireResistance, }, false, } -- s28765
L["aumenta la resistenza alla natura di %s. dura %s s"] = { { Stats.NatureResistance, }, false, } -- s28768
L["aumenta la resistenza all'ombra di %s. dura %s s"] = { { Stats.ShadowResistance, }, false, } -- s28769
L["aumenta la resistenza all'arcano di %s. dura %s s"] = { { Stats.ArcaneResistance, }, false, } -- s28770
L["aumenta la resistenza a tutte le scuole di magia di %s per %s s"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, } -- s28778
L["aumenta l'armatura del bersaglio amico di %s per %s s"] = { { Stats.Armor, }, false, } -- s28790
L["aumenta la potenza d'attacco del bersaglio amico di %s per %s s"] = { { Stats.GenericAttackPower, }, false, } -- s28791
L["aumenta la rigenerazione del mana del bersaglio amico di %s ogni %s s per %s s"] = { { Stats.GenericManaRegen, }, false, false, } -- s28795
L["rigenera %s mana in %s s. devi sederti per bere"] = { { Stats.GenericManaRegen, }, false, } -- s29007
L["aumenta la tempra di %s per %s ora"] = { { Stats.Stamina, }, false, } -- s29235
L["aumenta la potenza d'attacco di %s, e di %s in più ogni %s s. dura %s s"] = { { Stats.GenericAttackPower, }, { Stats.GenericAttackPower, }, false, false, ignoreSum = true } -- s29602
L["ammorba un nemico per %s min, aumentando i danni fisici che subisce di %s e riducendo la tempra di %s. il bersaglio ammorbato ha una probabilità del %s% di diffondere la malattia a uno degli alleati vicini quando viene colpito in combattimento"] = { false, false, { Stats.Stamina, }, false, reduction = true } -- s30081
L["aumenta la tempra per %s ora"] = { { Stats.Stamina, }, } -- s30088
L["increases stamina by %s when consumed"] = { { Stats.Stamina, }, } -- s30164
L["increases agility by %s when consumed"] = { { Stats.Agility, }, } -- s30173
L["increases intellect by %s when consumed"] = { { Stats.Intellect, }, } -- s30175
L["increases spirit by %s when consumed"] = { { Stats.Spirit, }, } -- s30177
L["increases strength by %s when consumed"] = { { Stats.Strength, }, } -- s30178
L["permanently enchant a %sh weapon to give %s agility"] = { false, { Stats.Agility, }, } -- s30229
L["riduce la probabilità di subire critici del %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, reduction = true } -- s30297
L["increases the player's spirit by %s and stamina by %s for %s ore.  you can only have the effect of one zanza potion at a time"] = { { Stats.Spirit, }, { Stats.Stamina, }, false, } -- s30336
L["increases your chance to hit while dual wielding by an additional %s%"] = { { Stats.MeleeHit, Stats.RangedHit, }, } -- s30816
L["increases critical chance of spells by %s%, melee and ranged by %s% and grants %s attack power. lasts %s ore"] = { { Stats.SpellCrit, }, { Stats.MeleeCrit, Stats.RangedCrit, }, { Stats.GenericAttackPower, }, false, } -- s355363
L["increases your dodge chance by %s%, and gives you a %s% chance to gain %s rage each time you dodge"] = { { Stats.Dodge, }, false, false, } -- s417051
L["un acido corrosivo che infligge %s danni da natura ogni %s s e riduce l'armatura del bersaglio di %s per %s s"] = { false, false, { Stats.Armor, }, false, reduction = true } -- s422996
L["increases your critical strike chance with spells by %s%. in addition, your critical healing spells heal the target for %s% of the healed amount over %s s"] = { { Stats.SpellCrit, }, false, false, } -- s429142
L["curses the target for %s min, reducing magic resistances by %s and increases magic damage taken by %s%. only one curse per warlock can be active on any one target"] = { false, { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, reduction = true } -- s440892
L["chance to hit with spells increased by %s%. not cumulative with other ring runes"] = { { Stats.SpellHit, }, } -- s442893
L["increases spell critical strike chance by %s%"] = { { Stats.SpellCrit, }, } -- s449933
L["aumenta la probabilità di critico con le armi a distanza del %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, }, } -- s462653
L["improves your chance to hit with all spells by %s%"] = { { Stats.MeleeHit, Stats.RangedHit, }, } -- s468275
L["increases the critical hit chance of spells by %s% for %s s. if shock and awe is engraved, gain an additional %s%"] = { { Stats.SpellCrit, }, false, false, } -- s468461
L["permanently enchant a shield to add %s% critical strike chance"] = { { Stats.MeleeCrit, Stats.RangedCrit, Stats.SpellCrit, }, } -- s1220623
L["increases your casting speed by %s%"] = { { Stats.SpellHaste, }, } -- s1220654
L["heal self for %s and increases strength by %s for %s s"] = { false, { Stats.Strength, }, false, } -- s1231124
L["restores %s mana and increases spell power by %s for %s s"] = { false, { Stats.SpellPower, }, false, } -- s1231138
L["increase defense by %s and armor by %s for %s s"] = { { Stats.Defense, }, { Stats.Armor, }, false, } -- s1231254
L["firing a regular ranged attack at a target prepares you for battle, increasing your defense by %s and melee attack speed by %s% for %s s"] = { { Stats.Defense, }, false, false, ignoreSum = true } -- s1231267
L["invoke the will of the mountain, increasing physical damage dealt by %s%, armor by %s, and size by %s% for %s s"] = { false, { Stats.Armor, }, false, false, } -- s1231289
L["strength increased\r\n by %s for %s s"] = { { Stats.Strength, }, false, } -- s1231339
L["agility increased by %s for %s s"] = { { Stats.Agility, }, false, } -- s1231406
L["increases the wielder's strength by %s for %s s"] = { { Stats.Strength, }, false, } -- s1231548
L["improves your chance to get a critical strike with all spells and attacks by %s%"] = { { Stats.MeleeCrit, Stats.RangedCrit, Stats.SpellCrit, }, } -- s1232052
L["%s attack power in cat, bear, and dire bear forms only"] = { { Stats.AttackPower, }, } -- s1232150
L["increases damage and healing done by magical spells and effects by up to %s"] = { { Stats.SpellPower, }, } -- s1232153
L["increases healing done by up to %s and damage done by up to %s for all magical spells and effects"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s1232158
L["increases your spirit by %s"] = { { Stats.Spirit, }, } -- s1232234
L["gives %s additional armor to nearby party members for %s s. players may only have one aura on them per paladin at any one time"] = { { Stats.Armor, }, false, } -- s1233344
L["reduces the chance for your attacks to be dodged or parried by %s%"] = { { Stats.DodgeReduction, Stats.ParryReduction, }, } -- s1234042
L["increases damage done by shadow spells and effects by up to %s"] = { { Stats.ShadowDamage, }, } -- s1234085
L["attaches a permanent scope to a bow or gun that increases its damage by %s"] = { { Stats.AverageWeaponDamage, }, } -- s1235011
L["increases the time between nearby enemies' attacks by %s%, slows their movement by %s%, and slow casting speed by %s% for %s s"] = { false, false, { Stats.SpellHaste, }, false, reduction = true } -- s1236220
L["attaches a permanent scope to a bow or gun that increases its chance to hit by %s%"] = { { Stats.MeleeHit, Stats.RangedHit, }, } -- s1237064
L["permanently enchant a bracer so it increases the wearer's agility by %s"] = { { Stats.Agility, }, } -- s1248460
L["permanently enchant bracers to give %s agility"] = { { Stats.Agility, }, } -- s1248500
L["infligge %s danni da ombra ogni %s s per %s min e riduce la forza della vittima per la durata della malattia"] = { { Stats.Strength, Stats.Stamina, }, false, false, reduction = true } -- s1249033
L["increases frost and shadow spell damage done by up to %s for %s s. this effect is doubled in snowy areas"] = { { Stats.FrostDamage, Stats.ShadowDamage, }, false, } -- s1249110
L["increases attack power by %s for %s s. this effect is doubled in volcanic areas"] = { { Stats.GenericAttackPower, }, false, } -- s1249113
L["your casts of greater heal in combat grant up to %s increased healing and up to %s increased damage for %s s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, false, ignoreSum = true } -- s1249118
L["your casts of healing touch in combat grant up to %s increased healing and up to %s increased damage for %s s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, false, ignoreSum = true } -- s1249118
L["your casts of healing wave in combat grant up to %s increased healing and up to %s increased damage for %s s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, false, ignoreSum = true } -- s1249118
L["your casts of holy light in combat grant up to %s increased healing and up to %s increased damage for %s s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, false, ignoreSum = true } -- s1249118
L["your casts of greater heal, healing touch, healing wave, or holy light in combat grant up to %s increased healing and up to %s increased damage for %s s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, false, ignoreSum = true } -- s1249118
L["increases healing done by up to %s and spell damage done by up to %s for %s s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, false, } -- s1249119
L["drink to gain %s agility and intellect. lasts for %s min"] = { { Stats.Agility, Stats.Intellect, }, false, } -- s1250918
L["drink to gain %s maximum health and %s armor. lasts for %s min"] = { { Stats.Health, }, { Stats.Armor, }, false, } -- s1250920
L["drink to increase healing done by spells and effects by up to %s. lasts %s min"] = { { Stats.HealingPower, }, false, } -- s1250922
L["drink to increase your maximum health by %s. lasts for %s min"] = { { Stats.Health, }, false, } -- s1250928
L["drink to restore %s health and %s mana every %s sec. lasts for %s min"] = { { Stats.HealthRegen, }, { Stats.GenericManaRegen, }, false, false, } -- s1250932
L["drink to increase your intellect by %s and chance to critically hit by %s%. lasts for %s min"] = { { Stats.Intellect, }, false, false, } -- s1250940
L["drink to increase your spirit by %s and chance to critically hit by %s%. lasts for %s min"] = { { Stats.Spirit, }, false, false, } -- s1250941
L["drink to regenerate %s mana every %s sec. lasts for %s min"] = { { Stats.GenericManaRegen, }, false, false, } -- s1250942
L["drink to increase spell damage by up to %s. lasts for %s min"] = { { Stats.SpellDamage, }, false, } -- s1250971
L["drink to increase nature spell damage by up to %s. lasts for %s min"] = { { Stats.NatureDamage, }, false, } -- s1250972
L["drink to increase your spirit by %s. lasts for %s min"] = { { Stats.Spirit, }, false, } -- s1250974
L["drink to increase your strength by %s. lasts for %s min"] = { { Stats.Strength, }, false, } -- s1250984
L["drink to increase your strength and agility by %s. lasts for %s min"] = { { Stats.Strength, Stats.Agility, }, false, } -- s1250985
L["drink to increase your strength by %s and chance to critically hit by %s%. lasts for %s min"] = { { Stats.Strength, }, false, false, } -- s1250986
L["drink to increase your intellect by %s. lasts for %s min"] = { { Stats.Intellect, }, false, } -- s1250988
L["increases spell damage by %s for %s s"] = { { Stats.SpellDamage, }, false, } -- s1251919
L["increases attack power by %s for %s s"] = { { Stats.GenericAttackPower, }, false, } -- s1251933
L["increases spell healing by %s for %s s"] = { { Stats.HealingPower, }, false, } -- s1251942
L["%s strength"] = { { Stats.Strength, }, } -- s1251984
L["permanently increase the stamina value by %s and the armor value by %s of an item worn on the chest, legs, hands, or feet"] = { { Stats.Stamina, }, { Stats.Armor, }, } -- s1254738
L["permanently increase the attack power value by %s and the armor value by %s of an item worn on the chest, legs, hands, or feet"] = { { Stats.GenericAttackPower, Stats.RangedAttackPower, }, { Stats.Armor, }, } -- s1254740
L["permanently increase the spell power value by %s and the armor value by %s of an item worn on the chest, legs, hands, or feet"] = { { Stats.SpellPower, }, { Stats.Armor, }, } -- s1254742
L["permanently increase the stamina value by %s and armor value by %s of an item worn on the chest, legs, hands, or feet. only usable on items level %s and above"] = { { Stats.Stamina, }, { Stats.Armor, }, false, } -- s1254747
L["emits a piercing shriek, inflicting %s nature damage and increasing the casting time of all spells by %s% for %s s"] = { false, { Stats.SpellHaste, }, false, reduction = true } -- s1264478
L["your tallstrider kicks up an abrasive cloud of dust, reducing the target's armor by %s for %s s"] = { { Stats.Armor, }, false, reduction = true } -- s1265899
L["restores %s health and %s mana over %s s. must remain seated while eating"] = { false, { Stats.GenericManaRegen, }, false, } -- s1269354
L["increases your ranged attack power by %s for %s s"] = { { Stats.RangedAttackPower, }, false, } -- s1288024
L["increases damage and healing done by magical spells and effects by up to %s. this effect is tripled in forest and grassland areas"] = { { Stats.SpellPower, }, } -- s1287561
L["increases all attributes by %s for %s s. effect and duration are doubled in forest and grassland areas"] = { { Stats.AllStats, }, false, } -- s1287571
L["increases your chance to dodge by %s% for %s s"] = { { Stats.Dodge, }, false, } -- s1287801
L["increases your spell hit chance by %s% for %s s"] = { { Stats.SpellHit, }, false, } -- s1287840
L["increases your armor by %s for %s s"] = { { Stats.Armor, }, false, } -- s1288016
L["increases your spell damage and healing by up to %s for %s s"] = { { Stats.SpellPower, }, false, } -- s1288020
L["increases your healing by up to %s for %s s"] = { { Stats.HealingPower, }, false, } -- s1288021
L["reduces an enemy's armor and resistances by %s for %s s. while affected, the target cannot use stealth or invisibility"] = { { Stats.Armor, Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, reduction = true } -- s1288561
L["hacks at the current target inflicting %s physical damage and reducing their armor by %s%"] = { false, { Stats.Armor, }, reduction = true } -- s1288908
L["increases the time between an enemy's attacks by %s% and its casting speed by %s%, adding a %s% chance to spread the contagion to an ally when hit"] = { false, { Stats.SpellHaste, }, false, reduction = true } -- s1289531
L["wounds the target for %s damage and increases the casting time of all spells by %s% for %s s"] = { false, { Stats.SpellHaste, }, false, reduction = true } -- s1290950
L["aumenta lo spirito di %s per %s s"] = { { Stats.Spirit, }, false, } -- s1291103
L["increases your block chance by %s% for %s s. this effect is doubled in strongholds and cities"] = { { Stats.BlockChance, }, false, } -- s1291105
L["increases the friendly target's armor by %s, all attributes by %s, and all resistances by %s for %s min"] = { { Stats.Armor, }, { Stats.AllStats, }, false, false, } -- s1291335
L["restores %s mana over %s s. must remain seated while drinking"] = { { Stats.GenericManaRegen, }, false, } -- s1291782
L["cause party members within %s yds to regenerate %s health every %s sec"] = { false, { Stats.HealthRegen, }, false, } -- s1292142
L["grants %s health and %s mana every %s sec for %s s when one of your spells is resisted"] = { { Stats.HealthRegen, }, { Stats.GenericManaRegen, }, false, false, ignoreSum = true } -- s1292594
L["inflict %s fire and %s frost damage, slow the target by %s% for %s s, reduce armor by %s, and inflict %s nature damage every %s sec for %s s"] = { false, false, false, false, { Stats.Armor, }, false, false, false, reduction = true } -- s1292657
L["increases damage done by arcane and shadow spells and effects by up to %s"] = { { Stats.ShadowDamage, Stats.ArcaneDamage, }, } -- s1292705
L["punctures target's armor, lowering it by %s"] = { { Stats.Armor, }, reduction = true } -- s1293005
L["when damaged, has a chance to grant you %s armor for %s s"] = { { Stats.Armor, }, false, ignoreSum = true } -- s1293342
L["%s% chance when struck in combat to gain %s mana per %s sec for %s s"] = { false, { Stats.GenericManaRegen, }, false, false, ignoreSum = true } -- s1293701
L["increases your stamina by %s. while in mount hyjal, hyjal summit, and the barrow deeps, you also gain %s% hit chance.\r\n\r\nlasts for %s ore. you can only have the effect of one flask at a time. this effect persists through death"] = { { Stats.Stamina, }, false, false, } -- s1293740
L["increases your stamina by %s. while in mount hyjal, hyjal summit, and the barrow deeps, you also gain %s% critical strike chance.\r\n\r\nlasts for %s ore. you can only have the effect of one flask at a time. this effect persists through death"] = { { Stats.Stamina, }, false, false, } -- s1293741
L["increases your stamina by %s. while in mount hyjal, hyjal summit, and the barrow deeps, you also gain %s% reduced chance to be dodged or parried.\r\n\r\nlasts for %s ore. you can only have the effect of one flask at a time. this effect persists through death"] = { { Stats.Stamina, }, false, false, } -- s1293742
L["increases your stamina by %s. while in mount hyjal, hyjal summit, and the barrow deeps, you also gain %s% haste.\r\n\r\nlasts for %s ore. you can only have the effect of one flask at a time. this effect persists through death"] = { { Stats.Stamina, }, false, false, } -- s1293743
L["increases your chance to dodge by %s% for %s s. this effect is doubled in strongholds and cities"] = { { Stats.Dodge, }, false, } -- s1293820
L["while in combat, your healing spells have a chance to grant an ally %s armor for %s s"] = { { Stats.Armor, }, false, ignoreSum = true } -- s1294064
L["increases armor by %s"] = { { Stats.Armor, }, } -- s1294065
L["increases your intellect by %s%"] = { { Stats.Strength, }, } -- s1294070
L["increases your attack power by %s"] = { { Stats.GenericAttackPower, }, } -- s1294071
L["your attacks have a chance to increase your attack power by %s and your healing spells have a chance to increase your intellect by %s for %s s"] = { { Stats.GenericAttackPower, }, { Stats.Strength, }, false, ignoreSum = true } -- s1294087
L["increases your chance to parry attacks by %s% for %s s"] = { { Stats.Parry, }, false, } -- s1294243
L["lash the enemy with the rage of sul'thraze, reducing their attack power by %s for %s s and dealing %s shadow damage. after %s s, the target suffers an additional %s shadow damage. this additional shadow damage deals %s times as much damage to trolls"] = { { Stats.GenericAttackPower, }, false, false, false, false, false, reduction = true } -- s1294430
L["increases your chance to hit with spells by %s%.\r\nincreases your chance to hit with attacks and abilities by %s%.\r\nreduces the chance for your attacks to be dodged by %s%.\r\nreduces the chance for your attacks to be parried by %s%"] = { { Stats.SpellHit, }, { Stats.MeleeHit, Stats.RangedHit, }, { Stats.DodgeReduction, }, { Stats.ParryReduction, }, } -- s1294788
L["increases damage and healing done by magical spells and effects by up to %s for %s s"] = { { Stats.SpellPower, }, false, } -- s1295233
L["summon a faithful rat familiar for %s ora. its presence increases your intellect by %s"] = { false, { Stats.Intellect, }, } -- s1296202
L["reduces target's attack power by %s for %s s"] = { { Stats.GenericAttackPower, }, false, reduction = true } -- s1297082
L["chance on harmful spell cast to reduce target's attack power by %s for %s s"] = { { Stats.GenericAttackPower, }, false, ignoreSum = true, reduction = true } -- s1297085
L["increased fist weapons %s"] = { { Stats.WeaponSkill, }, } -- s1297442
L["increases the ranged attack power of party members within %s yds by %s"] = { false, { Stats.RangedAttackPower, }, } -- s1299346
L["grants a chance when struck in combat to increase damage and healing done by magical spells and effects by up to %s for %s s"] = { { Stats.SpellDamage, }, false, ignoreSum = true } -- s1299743
L["increased defense %s"] = { { Stats.Defense, }, } -- s1300942
L["increased spirit %s"] = { { Stats.Spirit, }, } -- s1300943
L["reduces intellect by %s"] = { { Stats.Intellect, }, reduction = true } -- s1302206
L["increases your chance to dodge by %s% for %s s or until you dodge %s attacks"] = { { Stats.Dodge, }, false, false, } -- s1302264
L["summon a faithful frog familiar for %s ora. its presence increases your intellect by %s"] = { false, { Stats.Intellect, }, } -- s1302285
L["summon a faithful cat familiar for %s ora. its presence increases your intellect by %s"] = { false, { Stats.Intellect, }, } -- s1302303
L["chance on landing a damaging spell to assault the target's mind, increasing the casting time of all spells by %s% for %s s. stacks up to %s times"] = { { Stats.SpellHaste, }, false, false, ignoreSum = true, reduction = true } -- s1302341
L["all party members within %s yds are blessed, restoring %s health every %s sec"] = { false, { Stats.HealthRegen, }, false, } -- s1302375
L["completely unable to see, due to a blindfold covering her eyes, reducing her chance to hit with attacks by %s%"] = { { Stats.MeleeHit, Stats.RangedHit, }, reduction = true } -- s1303286
L["increases your attack speed by %s% and the physical damage you deal by %s for %s min"] = { false, { Stats.AverageWeaponDamage, }, false, } -- s1303979
L["increases critical chance of spells and attacks by %s%, increases attack power by %s, and increases spell damage and healing by up to %s for %s ore"] = { false, { Stats.GenericAttackPower, }, { Stats.SpellPower, }, false, } -- s1304452
L["increases hitpoints by %s. %s% haste to melee attacks. %s mana regen every %s sec"] = { { Stats.Health, }, { Stats.SpellHaste, }, { Stats.GenericManaRegen, }, false, } -- s1304594
L["increases hitpoints by %s. %s% haste to all spells and attacks. %s mana regen every %s sec"] = { { Stats.Health, }, { Stats.SpellHaste, }, { Stats.GenericManaRegen, }, false, } -- s1304678
L["increases the chance for a melee, ranged, or spell critical by %s% and all attributes by %s for %s ora"] = { false, { Stats.AllStats, }, false, } -- s1304690
L["increases attack power by %s and spell damage and healing by up to %s"] = { { Stats.GenericAttackPower, }, { Stats.SpellPower, }, } -- s1304759
L["kargra's eyes see beyond the mortal realms, reducing her chance to hit with attacks by %s%"] = { { Stats.MeleeHit, Stats.RangedHit, }, reduction = true } -- s1305855
L["increases healing done by up to %s and damage done by up to %s for all magical spells and effects. this effect is doubled at night"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s1306158
L["increases damage done by frost spells and effects by up to %s"] = { { Stats.FrostDamage, }, } -- s1306518
L["reduces your target's fire resistance by %s"] = { { Stats.FirePenetration, }, } -- s1306572
L["reduces your target's frost resistance by %s"] = { { Stats.FrostPenetration, }, } -- s1306580
L["restores %s mana per %s sec in wasteland areas"] = { { Stats.GenericManaRegen, }, false, } -- s1306632
L["increases healing done by up to %s and damage done by up to %s for all magical spells and effects while in mountainous areas"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s1306699
L["increases healing done by up to %s and damage done by up to %s for all magical spells and effects while in snowy areas"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s1306905
L["increases spirit by %s"] = { { Stats.Spirit, }, } -- s1307068
L["restores %s mana per %s sec in forest and grassland areas"] = { { Stats.GenericManaRegen, }, false, } -- s1308531
L["increases healing done by up to %s and damage done by up to %s for all magical spells and effects while in haunted areas"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s1307334
L["increases strength by %s while your inventory is full"] = { { Stats.Strength, }, } -- s1307762
L["increases healing done by up to %s and damage done by up to %s for all magical spells and effects. this effect is doubled during the day"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s1308023
L["healing increased by up to %s and damage done by up to %s for all magical spells and effects"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s1308024
L["increases damage and healing done by up to %s for all magical spells and effects. this effect is doubled in snowy areas"] = { { Stats.SpellPower, }, } -- s1308351
L["strength increased by %s in mountainous areas"] = { { Stats.Strength, }, } -- s1308764
L["increases healing done by up to %s and damage done by up to %s for all magical spells and effects. when you have not moved for %s sec, this effect is doubled"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, false, } -- s1309241
L["increases attack power by %s for %s s. this effect is doubled against demons"] = { { Stats.GenericAttackPower, }, false, } -- s1309318
L["increases ranged attack speed by %s%"] = { { Stats.RangedHaste, }, } -- s1309761
L["increases spell holy damage by up to %s for %s min"] = { { Stats.HolyDamage, }, false, } -- s1310077
L["transforms a random enemy within %s yards into a satyr for %s min sec. they're forced to speak demonic, and their casting speed is reduced by %s%"] = { false, false, { Stats.SpellHaste, }, reduction = true } -- s1310285
L["increases your pet's chance to dodge by %s% and decreases the time between your pet's attacks by %s% for %s s"] = { { Stats.Dodge, }, false, false, } -- s1310612
L["increases your chance to hit with your off hand weapon by %s%"] = { { Stats.MeleeHit, Stats.RangedHit, }, } -- s1311022
L["curses the target for %s min, reducing magic resistances by %s and increasing magic damage taken by %s%. only one curse per warlock can be active on any one target"] = { false, { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, false, reduction = true } -- s1311676
L["increases intellect by %s at night"] = { { Stats.Intellect, }, } -- s1315330
L["reduces the target enemy's attack power by %s for %s s"] = { { Stats.GenericAttackPower, }, false, reduction = true } -- s1315767
L["increase your agility by %s for %s s. if there is an elemental nearby, gain an additional %s"] = { { Stats.Agility, }, false, { Stats.Agility, }, } -- s1315878
L["your spells pierce %s magical resistances. gain an additional %s spell piercing in forest and grassland areas"] = { { Stats.SpellPenetration, }, { Stats.SpellPenetration, }, } -- s1315969
L["increases all resistances by %s. gain an additional %s to all resistances in forest and grassland areas"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, } -- s1315989
L["restores %s mana per %s sec. restores an additional %s mana per %s sec in forest and grassland areas"] = { { Stats.GenericManaRegen, }, false, { Stats.GenericManaRegen, }, false, } -- s1316053
L["kicks up dust, inflicting %s physical damage to enemies within %s yds and reducing hit chance with attacks by %s%"] = { false, false, { Stats.MeleeHit, Stats.RangedHit, }, reduction = true } -- s1316382
L["reduces the movement speed of an enemy by %s%, and reduces all physical and magical damage it deals by %s"] = { false, { Stats.SpellDamage, }, reduction = true } -- s1316489
L["chance on melee swing to become angry, increasing strength by %s for %s s"] = { { Stats.Strength, }, false, ignoreSum = true } -- s1317039
L["increases strength by %s"] = { { Stats.Strength, }, } -- s1317040
L["%s attack power. this effect is tripled in forest and grassland areas"] = { { Stats.GenericAttackPower, }, } -- s1318000
L["increases strength by %s while affected by a bleed"] = { { Stats.Strength, }, } -- s1318084
L["increases damage and healing done by magical spells and effects by up to %s. this effect is doubled in marsh and swamp areas"] = { { Stats.SpellPower, }, } -- s1318326
L["%s attack power. in haunted areas, gain an additional %s attack power"] = { { Stats.GenericAttackPower, }, { Stats.GenericAttackPower, }, } -- s1318328
L["increases spell damage and healing by up to %s. grants an additional %s spell damage against demons"] = { { Stats.SpellPower, }, false, } -- s1318476
L["restores %s mana per %s sec in haunted areas"] = { { Stats.GenericManaRegen, }, false, } -- s1318477
L["increases spirit by %s in forest and grassland areas"] = { { Stats.Spirit, }, } -- s1318478
L["increases spirit by %s in cavernous or underground areas"] = { { Stats.Spirit, }, } -- s1318480
L["increases spell damage and healing done by up to %s for %s s. this spell damage increase is doubled against dragonkin"] = { { Stats.SpellPower, }, false, } -- s1318930
L["chance on harmful spellcast to increase your spell damage and healing by up to %s for %s s. this spell damage increase is doubled against dragonkin"] = { { Stats.SpellDamage, }, false, ignoreSum = true } -- s1318931
L["%s attack power, doubled against mechanical units"] = { { Stats.GenericAttackPower, }, } -- s1318938
L["increase target creature's hit chance by %s%. stacks!"] = { { Stats.MeleeHit, Stats.RangedHit, }, } -- s1318987
L["%s attack power, doubled against undead targets"] = { { Stats.GenericAttackPower, }, } -- s1319047
L["increase target creature's spell hit chance by %s%. stacks!"] = { { Stats.SpellHit, }, } -- s1319206
L["increase target creature's haste by %s%. stacks!"] = { { Stats.SpellHaste, }, } -- s1319446
L["increases healing done by up to %s and damage done by up to %s for all magical spells and effects. this effect is doubled in strongholds and cities"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- s1320330
L["riduce la velocità di lancio di un nemico del %s% per %s min"] = { { Stats.SpellHaste, }, false, reduction = true } -- s8272
L["riduce la potenza d'attacco in mischia e a distanza dei nemici vicini di %s per %s min"] = { { Stats.GenericAttackPower, }, false, reduction = true } -- s28342
L["aumenta l'intervallo tra gli attacchi di un nemico del %s% e riduce la sua velocità di movimento del %s%, oltre a ridurre la forza del %s%. dura %s s"] = { false, { Stats.GenericAttackPower, }, false, false, reduction = true } -- s402811
L["la probabilità di schivata del druido aumenta del %s% per %s s"] = { { Stats.Dodge, }, false, } -- s412800
L["aumenta la velocità d'attacco a distanza del %s% per %s s"] = { { Stats.RangedHaste, }, false, } -- s428726
L["tiro piumato infligge %s danni da natura"] = { { Stats.FireResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, Stats.NatureResistance, }, reduction = true } -- s434841
L["circonda l'incantatore con uno scudo di fulmini che dura %s s e infligge %s danni da natura agli attaccanti in mischia"] = { false, { Stats.Strength, }, } -- s436471
L["rigenera %s mana e %s salute"] = { { Stats.SpellDamage, }, { Stats.GenericManaRegen, }, } -- s448084
L["increases your critical strike chance while in bear, dire bear or cat form by %s%"] = { { Stats.MeleeHit, Stats.RangedHit, Stats.SpellHit, }, } -- s449926
L["aumenta i danni inflitti da spine di %s e la durata del %s%"] = { { Stats.MeleeHit, Stats.RangedHit, }, { Stats.SpellHit, }, } -- s455858
L["riduce gli attributi dei nemici vicini di %s per %s s"] = { { Stats.AllStats, }, false, reduction = true } -- s1223265
L["restores %s mana per %s sec to your imp"] = { { Stats.GenericManaRegen, }, false, } -- s1302363
L["teaches you how to permanently enchant a piece of chest armor to give %s intellect"] = { { Stats.Intellect, }, } -- i6342
L["teaches you how to temporarily imbue a piece of chest armor to give %s spirit for %s min"] = { { Stats.Spirit, }, false, } -- i6222
L["teaches you how to permanently enchant a bracer to give %s spirit"] = { { Stats.Spirit, }, } -- i6344
L["teaches you how to permanently enchant a bracer to give %s strength"] = { { Stats.Strength, }, } -- i6347
L["teaches you how to permanently enchant a two-handed weapon so it grants %s intellect"] = { { Stats.Intellect, }, } -- i6349
L["teaches you how to permanently enchant a pair of boots to grant %s agility"] = { { Stats.Agility, }, } -- i6377
L["teaches you how to permanently enchant a two-handed weapon so it grants %s spirit"] = { { Stats.Spirit, }, } -- i11038
L["teaches you how to permanently enchant a cloak so it grants %s agility"] = { { Stats.Agility, }, } -- i11039
L["teaches you how to permanently enchant a shield with %s armor"] = { { Stats.Armor, }, } -- i11081
L["teaches you how to permanently enchant a cloak so it grants %s shadow resistance"] = { { Stats.ShadowResistance, }, } -- i11098
L["teaches you how to permanently enchant a shield to grant %s% blocking"] = { { Stats.BlockChance, }, } -- i11168
L["teaches you how to permanently enchant a shield to grant %s stamina"] = { { Stats.Stamina, }, } -- i11202
L["teaches you how to permanently enchant a bracer to give %s defense"] = { { Stats.Defense, }, } -- i11223
L["teaches you how to permanently enchant a shield to grant %s frost resistance"] = { { Stats.FrostResistance, }, } -- i11224
L["teaches you how to permanently enchant a bracer to give %s stamina"] = { { Stats.Stamina, }, } -- i11225
L["teaches you how to permanently enchant a bracer to give %s intellect"] = { { Stats.Intellect, }, } -- i16214
L["teaches you how to permanently enchant a pair of boots to grant %s stamina"] = { { Stats.Stamina, }, } -- i16215
L["teaches you how to permanently enchant a cloak so it adds %s to all resistances"] = { { Stats.FireResistance, Stats.NatureResistance, Stats.FrostResistance, Stats.ShadowResistance, Stats.ArcaneResistance, }, } -- i16216
L["teaches you how to permanently enchant gloves to give %s agility"] = { { Stats.Agility, }, } -- i16219
L["teaches you how to permanently enchant a pair of boots to grant %s spirit"] = { { Stats.Spirit, }, } -- i16220
L["teaches you how to permanently enchant a piece of chest armor to give %s stamina"] = { { Stats.Stamina, }, } -- i16221
L["teaches you how to permanently enchant a shield to grant %s spirit"] = { { Stats.Spirit, }, } -- i16222
L["teaches you how to permanently enchant a cloak to give %s additional armor"] = { { Stats.Armor, }, } -- i16224
L["teaches you how to permanently enchant a two-handed weapon to do %s additional damage"] = { { Stats.AverageWeaponDamage, }, } -- i16247
L["teaches you how to permanently enchant a weapon to do %s additional damage"] = { { Stats.AverageWeaponDamage, }, } -- i16250
L["teaches you how to permanently enchant a weapon to grant up to %s additional frost damage when casting frost spells"] = { { Stats.FrostDamage, }, } -- i17725
L["teaches you how to permanently enchant a weapon to add up to %s damage to spells"] = { { Stats.SpellPower, }, } -- i18259
L["teaches you how to permanently enchant a weapon to add up to %s points of healing to healing spells and up to %s points of damage to damage spells"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- i18260
L["teaches you how to permanently enchant a weapon to increase your strength by %s"] = { { Stats.Strength, }, } -- i19444
L["teaches you how to permanently enchant a weapon to increase your agility by %s"] = { { Stats.Agility, }, } -- i19445
L["teaches you how to permanently enchant a bracer to restore %s mana every %s seconds"] = { { Stats.GenericManaRegen, }, false, } -- i19446
L["teaches you how to permanently enchant a bracer to increase the effects of healing spells by %s and the effects of your damage spells by %s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- i19447
L["teaches you how to permanently enchant a weapon to increase your spirit by %s"] = { { Stats.Spirit, }, } -- i19448
L["teaches you how to permanently enchant a weapon to increase your intellect by %s"] = { { Stats.Intellect, }, } -- i19449
L["teaches you how to permanently enchant gloves to increase the shadow damage done by spells and abilities by %s"] = { { Stats.ShadowDamage, }, } -- i20727
L["teaches you how to permanently enchant gloves to increase the frost damage done by spells and abilities by %s"] = { { Stats.FrostDamage, }, } -- i20728
L["teaches you how to permanently enchant gloves to increase the fire damage done by spells and abilities by %s"] = { { Stats.FireDamage, }, } -- i20729
L["teaches you how to permanently enchant gloves to increase the healing done by spells and abilities by up to %s and damage spells by up to %s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- i20730
L["teaches you how to permanently enchant gloves to increase agility by %s"] = { { Stats.Agility, }, } -- i20731
L["teaches you how to permanently enchant a cloak to increase fire resistance by %s"] = { { Stats.GenericAttackPower, }, } -- i20732
L["teaches you how to permanently enchant a cloak to increase nature resistance by %s"] = { { Stats.NatureResistance, }, } -- i20733
L["teaches you how to permanently enchant a cloak to increase dodge chance by %s%"] = { { Stats.Dodge, }, } -- i20736
L["teaches you how to permanently enchant a two-handed weapon to increase your agility by %s"] = { { Stats.Agility, }, } -- i22392
L["teaches you how to permanently enchant a shield to add up to %s damage to spells and up to %s healing to healing spells"] = { { Stats.SpellDamage, }, { Stats.HealingPower, }, } -- i228982
L["teaches you how to permanently enchant bracers to give %s intellect"] = { { Stats.Intellect, }, } -- i249474
L["teaches you how to permanently enchant bracers to increase healing power by up to %s and spell damage by up to %s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- i249475
L["teaches you how to permanently enchant bracers to give %s agility"] = { { Stats.Agility, }, } -- i249486
L["teaches you how to permanently enchant a necklace to give %s strength"] = { { Stats.Strength, }, } -- i249496
L["teaches you how to permanently enchant a necklace to increase spell damage and healing by up to %s"] = { { Stats.SpellPower, }, } -- i249502
L["teaches you how to permanently enchant a necklace to increase healing power by up to %s and spell damage by up to %s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- i249503
L["teaches you how to permanently enchant a necklace to give %s agility"] = { { Stats.Agility, }, } -- i249504
L["teaches you how to permanently enchant a two-handed melee weapon to grant %s strength"] = { { Stats.Strength, }, } -- i249513
L["teaches you how to permanently enchant a two-handed melee weapon to increase strength by %s"] = { { Stats.Strength, }, } -- i249523
L["teaches you how to permanently enchant a two-handed melee weapon to increase spell damage and healing by up to %s"] = { { Stats.SpellPower, }, } -- i249525
L["teaches you how to permanently enchant a two-handed melee weapon to increase healing power by up to %s and spell damage by up to %s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- i249526
L["teaches you how to permanently enchant an off-hand to give %s intellect"] = { { Stats.Intellect, }, } -- i274391
L["teaches you how to permanently enchant an off-hand to give %s spirit"] = { { Stats.Spirit, }, } -- i274392
L["teaches you how to permanently enchant an off-hand to give %s intellect and %s spirit"] = { { Stats.Intellect, }, { Stats.Spirit, }, } -- i274393
L["teaches you how to permanently enchant a two-handed melee weapon to increase spell power by %s"] = { { Stats.SpellPower, }, } -- i274394
L["teaches you how to permanently enchant a shield to give %s stamina"] = { { Stats.Stamina, }, } -- i274395
L["teaches you how to permanently enchant gloves to give %s strength"] = { { Stats.Strength, }, } -- i274398
L["teaches you how to permanently enchant cloaks to give %s agility"] = { { Stats.Agility, }, } -- i274399
L["teaches you how to permanently enchant a shield to give %s% critical strike chance"] = { { Stats.MeleeCrit, Stats.RangedCrit, Stats.SpellCrit, }, } -- i274400
L["teaches you how to permanently enchant bracers to give %s spell power"] = { { Stats.SpellPower, }, } -- i274401
L["stamina %s and armor %s"] = { { Stats.Stamina, }, { Stats.Armor, }, } -- e15
L["armor %s"] = { { Stats.Armor, }, } -- e16
L["mirino (%s danni)"] = { { Stats.AverageWeaponDamage, }, } -- e30
L["%s danni"] = { { Stats.AverageWeaponDamage, }, } -- e67
L["weapon damage %s"] = { { Stats.AverageWeaponDamage, }, } -- e250
L["%s agilità e %s spirito"] = { { Stats.Agility, }, { Stats.Spirit, }, } -- e583
L["%s agilità e %s intelletto"] = { { Stats.Agility, }, { Stats.Intellect, }, } -- e584
L["%s agilità e %s tempra"] = { { Stats.Agility, }, { Stats.Stamina, }, } -- e585
L["%s agilità e %s forza"] = { { Stats.Agility, }, { Stats.Strength, }, } -- e586
L["%s intelletto / %s spirito"] = { { Stats.Intellect, }, { Stats.Spirit, }, } -- e587
L["%s intelletto e %s tempra"] = { { Stats.Intellect, }, { Stats.Stamina, }, } -- e588
L["%s intelletto e %s forza"] = { { Stats.Intellect, }, { Stats.Strength, }, } -- e589
L["%s spirito / %s tempra"] = { { Stats.Spirit, }, { Stats.Stamina, }, } -- e590
L["%s spirito / %s forza"] = { { Stats.Spirit, }, { Stats.Strength, }, } -- e591
L["%s tempra e %s forza"] = { { Stats.Stamina, }, { Stats.Strength, }, } -- e592
L["intellect %s"] = { { Stats.Intellect, }, } -- e723
L["strength %s"] = { { Stats.Strength, }, } -- e823
L["all stats %s"] = { { Stats.AllStats, }, } -- e847
L["%s potenza d'attacco"] = { { Stats.AttackPower, Stats.RangedAttackPower, }, } -- e1563
L["pietra del fuoco %s"] = { { Stats.SpellCrit, }, } -- e1803
L["%s stamina"] = { { Stats.Stamina, }, } -- e1892
L["%s potenza d'attacco a distanza"] = { { Stats.RangedAttackPower, }, } -- e2040
L["%s potenza magica (arcano)"] = { { Stats.ArcaneDamage, }, } -- e2079
L["%s potenza magica (ombra)"] = { { Stats.ShadowDamage, }, } -- e2117
L["%s potenza magica (fuoco)"] = { { Stats.FireDamage, }, } -- e2155
L["%s potenza magica (sacro)"] = { { Stats.HolyDamage, }, } -- e2193
L["%s potenza magica (gelo)"] = { { Stats.FrostDamage, }, } -- e2231
L["%s potenza magica (natura)"] = { { Stats.NatureDamage, }, } -- e2269
L["%s mana ogni %s s"] = { { Stats.GenericManaRegen, }, false, } -- e2363
L["%s salute ogni %s s"] = { { Stats.HealthRegen, }, false, } -- e2401
L["%s fire resistance"] = { { Stats.FireResistance, }, } -- e2463
L["healing spells %s/damage spells %s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- e2617
L["%s indice di schivata"] = { { Stats.DodgeRating, }, } -- e2815
L["%s indice di critico"] = { { Stats.CritRating, }, } -- e2823
L["%s indice di blocco"] = { { Stats.BlockRating, }, } -- e2826
L["%s indice di celerità"] = { { Stats.HasteRating, }, } -- e3726
L["%s hp"] = { { Stats.Health, }, } -- e7565
L["%s spell power"] = { { Stats.SpellPower, }, } -- e7655
L["%s agility"] = { { Stats.Agility, }, } -- e7656
L["poultry precision scope (%s damage)"] = { { Stats.AverageWeaponDamage, }, } -- e7944
L["poultry precision scope (%s% hit)"] = { { Stats.MeleeHit, Stats.RangedHit, }, } -- e8057
L["agility %s"] = { { Stats.Agility, }, } -- e8204
L["healing spells %s, damage spells %s"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- e8208
L["spell power %s"] = { { Stats.SpellPower, }, } -- e8211
L["spell power %s and armor %s"] = { { Stats.SpellPower, }, { Stats.Armor, }, } -- e8482
L["attack power %s and armor %s"] = { { Stats.AttackPower, Stats.RangedAttackPower, }, { Stats.Armor, }, } -- e8483
L["%s healing power & %s spell damage"] = { { Stats.HealingPower, }, { Stats.SpellDamage, }, } -- e8694
L["defense %s and stamina %s"] = { { Stats.DefenseRating, }, { Stats.Stamina, }, } -- e8719
